[tool.black]
line-length = 120
target-version = ["py310"]
color = true

[tool.mypy]
allow_redefinition = true

[[tool.mypy.overrides]]
module = [
    "cv2",
    "PIL",
    "PIL.Image",
    "pydirectinput",
    "tesserocr",
    "win32con",
    "win32gui",
    "win32ui",
]
ignore_missing_imports = true
